### PR TITLE
Remove supporting code for 1.6.0 alpha and beta builds

### PR DESCRIPTION
**Pull request by jjshanks**
Tested on both Ubuntu and Powershell.

### CODE REVIEW

**Review by janosdebugs — COMMENTED** [review]
Thank you, looks good, we just have to figure out when to merge it.

**Comment by janosdebugs** [comment]
Hey @jjshanks we'll wait another 2 weeks to give people enough time to migrate to the stable release and then we can merge it. Thank you for your help!

**Comment by janosdebugs** [comment]
@opentofu/core-engineers I believe it's been long enough, what do you think of merging this?

**Comment by Yantrio** [comment]
@janosdebugs I'm happy to merge this.

**Review by Yantrio — APPROVED** [review]

**Review by janosdebugs — APPROVED** [review]

**Pull request merged**
